tengstrom_demo.tengstrom_demo_content_type.*:
  type: config_entity
  label: 'Demo Content type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
